model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    n_embed: 4096
    embed_dim: 4
    monitor: "val/rec_loss"

    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        codebook_weight: 1.0
        use_actnorm: False
        disc_start: 40001
        disc_weight: 1.0
        disc_in_channels: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 3
    train:
      target: taming.data.lsun.LSUNChurchesTrain
    validation:
      target: taming.data.lsun.LSUNChurchesValidation
