model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.RVQTransformer
  params:
    z_codebook_level: 1
    unconditional: False
    cond_on_prev_level: True
    joint_training: False
    transformer_config:
      target: taming.modules.transformer.mingpt.CodeGPT
      params:
        cross_attention: True
        in_channels: 1024
        vocab_size: 0    #Is overwritten for RVQTransformer
        block_size: 65
        n_layer: 24
        n_head: 16
        n_embd: 256
    first_stage_config:
      target: taming.models.vqgan.ResidualVQModel
      params:
        ckpt_path: "/export/home/fmayer/taming-transformers/logs/2022-04-08T16-00-26_lee_2022_setup_8x8/checkpoints/epoch=000004.ckpt"
        n_embed: 666
        level_sizes:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        layer_weights:
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        n_embeds:
        - 4096
        - 4096
        - 4096
        - 4096
        n_levels: 4
        embed_dim: 1024
        monitor: val/rec_loss
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss

    cond_stage_config:
      target: taming.modules.misc.coord.CoordStage
      params:
        n_embed: 4096
        down_factor: 16

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 48
    num_workers: 12
    train:
      target: taming.data.lsun.LSUNChurchesTrain
      params:
        size: 256
    validation:
      target: taming.data.lsun.LSUNChurchesValidation
      params:
        size: 256
