model:
  base_learning_rate: 2.86e-6
  target: taming.models.vqgan.ResidualVQModel
  params:
    n_embed: 666 #dummy, unused
    level_sizes: [1.0, 1.0, 1.0, 1.0]   # relative to encoder-output, e.g. for 32x32: 8x8 -> 16x16 -> 32x32 -> 32x32
    layer_weights: [0., 0., 0., 1.]
    n_embeds: [2048,2048,2048,2048]
    n_levels: 4
    shared_codebook: True
    embed_dim: 256
    monitor: "val/rec_loss"

    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 256
      ch_mult: [1,2,2,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.ResidualVQLPIPSWithDiscriminator
      params:
        quantize_scale_weights: [1., 1., 1., 1.]
        codebook_weight: 1.0
        n_classes: [2048,2048,2048,2048]
        use_actnorm: False
        disc_start: 25006 #5 warmup epochs of 5001 batches (for bs 14)
        disc_weight: 0.75
        disc_in_channels: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    train:
      target: taming.data.faceshq.FFHQTrain
      params:
        size: 256
    validation:
      target: taming.data.faceshq.FFHQValidation
      params:
        size: 256
