model:
  base_learning_rate: 4.5e-06
  target: kim_src.models.autoencoders.VQModel
  params:
    embed_dim: 3
    n_embed: 256
    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,4]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: kim_src.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        codebook_weight: 1.0
        disc_start: 10000
        n_classes: 256

data:
  target: kim_src.data.utils.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: kim_src.data.faceshq.FFHQTrain
      params:
        size: 256
    validation:
      target: kim_src.data.faceshq.FFHQValidation
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: kim_utils.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        log_on_batch_idx: True
        log_first_step: True
    revive_callback:
      target: kim_src.modules.vqvae.quantize.CodebookReviver
      params:
        dset_cfg:
          target: kim_src.data.faceshq.FFHQValidation
          params:
            size: 256
        num_data: 5000
        step_freq: 2000
        min_steps: 0
        vocab_size: 256

  modelcheckpoint:
    params:
      every_n_train_steps: 2000

  trainer:
    benchmark: True
    num_sanity_val_steps: 0
